image: mcr.microsoft.com/playwright/python:v1.58.0-jammy

stages:
  - test

variables:
  BROWSER: "chrome"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - playwright install-deps
  - playwright install

run_tests:
  stage: test
  script:
    - pytest tests/ -v --tb=short --browser_name=$BROWSER
  artifacts:
    when: always
    paths:
      - reports/
    expire_in: 7 days