[pytest]
markers =
    ui: UI end to end tests
    api: API and hybrid tests
    network: Network interception tests
    bdd: BDD scenario tests

addopts =
    -v
    --tb=short

testpaths =
    tests
    bdd

